services:
  code-server:
    build: .
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HASHED_PASSWORD_B64=${HASHED_PASSWORD_B64}
      - SUDO_PASSWORD_HASH=${SUDO_PASSWORD_HASH}
      - PORT=${PORT}
    volumes:
      - ./config:/config
      - ./workspace:/config/workspace
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
    depends_on:
      - code-server
    restart: unless-stopped

volumes:
  caddy_data:
